"""Builds supabase/migrations/*_geo_data.sql from GeoNames dumps (CC BY 4.0, https://www.geonames.org).

Usage:
  curl -LO https://download.geonames.org/export/dump/cities5000.zip && unzip cities5000.zip
  curl -LO https://download.geonames.org/export/dump/admin1CodesASCII.txt
  curl -LO https://download.geonames.org/export/dump/admin2Codes.txt
  python scripts/build-geo-migration.py <dir with the files> <cities .sql> [<provinces .sql>]

Populated places become cities; "sections of populated places" (PPLX) become neighborhoods of the
nearest large city within 15 km.
"""

import math
import re
import sys
import unicodedata
from pathlib import Path

COUNTRIES = {"ES": "Spain", "FR": "France", "IT": "Italy", "PT": "Portugal"}
NEIGHBORHOOD_PARENT_MIN_POP = 100_000

# GeoNames' main name is sometimes the English exonym; people search in the local language.
LOCAL_NAMES = {
    "Lisbon": "Lisboa", "Rome": "Roma", "Milan": "Milano", "Naples": "Napoli", "Turin": "Torino",
    "Florence": "Firenze", "Genoa": "Genova", "Padua": "Padova", "Venice": "Venezia", "Mantua": "Mantova",
    "Syracuse": "Siracusa", "Seville": "Sevilla", "Saragossa": "Zaragoza",
    "Gasteiz / Vitoria": "Vitoria-Gasteiz", "Donostia / San Sebastián": "San Sebastián",
}
# Feature codes that are districts of a bigger city (arrondissements, city sections).
SECTION_CODES = {"PPLX", "PPLA5"}
SKIP_CODES = {"PPLQ", "PPLH", "PPLCH", "PPLW"}
SECTION_NAME = re.compile(r"^(Paris|Marseille|Lyon) \d")
KNOWN_SECTIONS = {"Ciudad Lineal"}
NEIGHBORHOOD_MAX_KM = 15


def slugify(value: str) -> str:
    ascii_value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", "-", ascii_value.lower()).strip("-")


def sql_text(value: str | None) -> str:
    return "null" if value is None else "'" + value.replace("'", "''") + "'"


def km(a, b) -> float:
    lat1, lon1, lat2, lon2 = map(math.radians, (a[0], a[1], b[0], b[1]))
    h = math.sin((lat2 - lat1) / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin((lon2 - lon1) / 2) ** 2
    return 6371 * 2 * math.asin(math.sqrt(h))


def main(src: Path, out: Path, provinces_out: Path | None = None) -> None:
    regions = {}
    for line in (src / "admin1CodesASCII.txt").read_text(encoding="utf-8").splitlines():
        code, name, *_ = line.split("\t")
        regions[code] = name

    cities, sections = [], []
    for line in (src / "cities5000.txt").read_text(encoding="utf-8").splitlines():
        f = line.split("\t")
        country = f[8]
        if country not in COUNTRIES:
            continue
        if f[7] in SKIP_CODES:
            continue
        name = LOCAL_NAMES.get(f[1], f[1])
        row = {
            "geonameid": f[0],
            "name": name,
            "lat": float(f[4]),
            "lng": float(f[5]),
            "feature": f[7],
            "country": country,
            "region": regions.get(f"{country}.{f[10]}"),
            "admin1": f[10],
            "admin2": f[11],
            "population": int(f[14] or 0),
        }
        is_section = row["feature"] in SECTION_CODES or SECTION_NAME.match(name) or name in KNOWN_SECTIONS
        (sections if is_section else cities).append(row)

    cities.sort(key=lambda r: -r["population"])
    used: set[tuple[str, str]] = set()
    for c in cities:
        slug = slugify(c["name"])
        if (c["country"], slug) in used and c["region"]:
            slug = f"{slug}-{slugify(c['region'])}"
        if (c["country"], slug) in used:
            slug = f"{slug}-{c['geonameid']}"
        used.add((c["country"], slug))
        c["slug"] = slug

    big = [c for c in cities if c["population"] >= NEIGHBORHOOD_PARENT_MIN_POP]
    hoods = []
    for s in sections:
        candidates = [(km((s["lat"], s["lng"]), (c["lat"], c["lng"])), c) for c in big if c["country"] == s["country"]]
        if not candidates:
            continue
        dist, parent = min(candidates, key=lambda t: t[0])
        if dist <= NEIGHBORHOOD_MAX_KM:
            hoods.append((parent, s))

    lines = [
        "-- Generated by scripts/build-geo-migration.py from GeoNames (CC BY 4.0). Do not edit by hand.",
        "insert into public.countries (code, name) values "
        + ", ".join(f"('{k}', '{v}')" for k, v in COUNTRIES.items())
        + " on conflict (code) do nothing;",
        "",
    ]
    for i in range(0, len(cities), 500):
        chunk = cities[i : i + 500]
        values = ",\n".join(
            f"('{c['country']}', {sql_text(c['name'])}, '{c['slug']}', {sql_text(c['region'])}, {c['population']}, "
            f"'SRID=4326;POINT({c['lng']} {c['lat']})')"
            for c in chunk
        )
        lines.append(
            "insert into public.cities (country_code, name, slug, region, population, location) values\n"
            + values
            + "\non conflict (country_code, slug) do nothing;\n"
        )

    seen: set[tuple[str, str, str]] = set()
    hood_values = []
    for parent, s in hoods:
        # "Paris 15 Vaugirard" -> "15 Vaugirard" inside Paris.
        if s["name"].startswith(parent["name"] + " "):
            s = {**s, "name": s["name"][len(parent["name"]) + 1 :]}
        slug = slugify(s["name"])
        key = (parent["country"], parent["slug"], slug)
        if not slug or key in seen:
            continue
        seen.add(key)
        hood_values.append(
            f"('{parent['country']}', '{parent['slug']}', {sql_text(s['name'])}, '{slug}', "
            f"'SRID=4326;POINT({s['lng']} {s['lat']})')"
        )
    for i in range(0, len(hood_values), 500):
        lines.append(
            "insert into public.neighborhoods (city_id, name, slug, location)\n"
            "select c.id, v.name, v.slug, v.location::extensions.geography from (values\n"
            + ",\n".join(hood_values[i : i + 500])
            + "\n) as v(country_code, city_slug, name, slug, location)\n"
            "join public.cities c on c.country_code = v.country_code and c.slug = v.city_slug\n"
            "on conflict (city_id, slug) do nothing;\n"
        )

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(cities)} cities, {len(hood_values)} neighborhoods -> {out}")
    if provinces_out:
        write_provinces(src, cities, regions, provinces_out)


# Spanish exonyms people actually search for, instead of the co-official spellings.
PROVINCE_NAMES = {"Lisbon": "Lisboa", "Roma Capitale": "Roma", "Florence": "Firenze", "Upper Garonne": "Haute-Garonne", "South Corsica": "Corse-du-Sud", "Upper Corsica": "Haute-Corse", "Araba / Álava": "Álava", "València": "Valencia", "Castelló": "Castellón", "Illes Balears": "Baleares", "Alacant": "Alicante"}
PROVINCE_PREFIX = re.compile(
    r"^(Province of|Provincia de|Província de|Provincia di|Provincia del|Provincia dell'|Città metropolitana di|"
    r"Metropolitan City of|Département de la|Département de l'|Département des|Département du|Département de)\s*",
    re.IGNORECASE,
)


def write_provinces(src: Path, cities, regions, out: Path) -> None:
    """Province level for breadcrumbs and landing pages: admin2 in ES/FR/IT, districts (admin1) in PT."""
    admin2 = {}
    for line in (src / "admin2Codes.txt").read_text(encoding="utf-8").splitlines():
        code, name, *_ = line.split("\t")
        admin2[code] = name

    provinces: dict[str, dict] = {}
    city_province: list[tuple[str, str, str]] = []
    for c in cities:
        if c["country"] == "PT":
            code, raw = f"PT.{c['admin1']}", regions.get(f"PT.{c['admin1']}")
        else:
            code = f"{c['country']}.{c['admin1']}.{c['admin2']}"
            raw = admin2.get(code)
        if not raw:
            continue
        if code not in provinces:
            name = PROVINCE_PREFIX.sub("", raw).strip()
            name = PROVINCE_NAMES.get(name, name)
            provinces[code] = {"code": code, "country": c["country"], "name": name}
        city_province.append((c["country"], c["slug"], code))

    used: set[tuple[str, str]] = set()
    for prov in sorted(provinces.values(), key=lambda p: p["code"]):
        slug = slugify(prov["name"])
        if (prov["country"], slug) in used:
            slug = f"{slug}-{slugify(prov['code'].split('.')[-1])}"
        used.add((prov["country"], slug))
        prov["slug"] = slug

    lines = [
        "-- Generated by scripts/build-geo-migration.py from GeoNames (CC BY 4.0). Do not edit by hand.",
        "insert into public.provinces (country_code, code, name, slug) values",
        ",\n".join(f"('{p['country']}', '{p['code']}', {sql_text(p['name'])}, '{p['slug']}')" for p in provinces.values()),
        "on conflict (code) do nothing;",
        "",
    ]
    for i in range(0, len(city_province), 1000):
        chunk = city_province[i : i + 1000]
        lines.append(
            "update public.cities c set province_id = p.id from (values\n"
            + ",\n".join(f"('{country}', '{slug}', '{code}')" for country, slug, code in chunk)
            + "\n) as v(country_code, city_slug, province_code)\n"
            "join public.provinces p on p.code = v.province_code\n"
            "where c.country_code = v.country_code and c.slug = v.city_slug;\n"
        )
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(provinces)} provinces, {len(city_province)} city links -> {out}")


if __name__ == "__main__":
    main(Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3]) if len(sys.argv) > 3 else None)
